import Hero from '@/components/Hero/Hero';
import Header from '@/components/Shared/Header/Header';
import TopRated from '@/components/TopRated/TopRated';
import Head from 'next/head';

import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

export default function Home({ homes = [] }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <div className="container mx-auto px-3 lg:px-4">
          <Hero />
          <TopRated homesList={homes} />
        </div>
      </main>
    </>
  );
}

export async function getStaticProps() {
  const homes = await prisma.home.findMany();
  return {
    props: {
      homes: JSON.parse(JSON.stringify(homes)),
    },
  };
}
