import styles from '@/styles/Home.module.css';
import { Inter } from 'next/font/google';
import Head from 'next/head';
import Link from 'next/link';
import { getSortedPostsData } from '../lib/posts';

const inter = Inter({ subsets: ['latin'] });

export default function Home({ allPostsData }: any) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>Hi There!</p>
          <div>
            <a
              href="https://kapindra.com.np"
              target="_blank"
              rel="noopener noreferrer"
            >
              I am here!
            </a>
          </div>
        </div>

        <div className={styles.grid}>
          {allPostsData.map(({ id, date, title }: any) => (
            <Link
              href={`/posts/` + id}
              className={styles.card}
              rel="noopener noreferrer"
              key={id}
            >
              <h2 className={inter.className}>{title}</h2>
              <p className={inter.className}>{date}</p>
            </Link>
          ))}
        </div>
      </main>
    </>
  );
}

export async function getStaticProps() {
  const allPostsData = getSortedPostsData();
  return {
    props: {
      allPostsData,
    },
  };
}
